---
- name: config | Create restic-env
  ansible.builtin.template:
    src: "restic-env.j2"
    dest: "{{ restic_config_path }}/restic-env"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: config | Create restic-includes
  ansible.builtin.template:
    src: "restic-includes.j2"
    dest: "{{ restic_config_path }}/restic-includes"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: config | Create restic-excludes
  ansible.builtin.template:
    src: "./restic-excludes.j2"
    dest: "{{ restic_config_path }}/restic-excludes"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: config | Create restic-backup
  ansible.builtin.template:
    src: "./restic-backup.j2"
    dest: "{{ restic_bin_system_path }}/restic-backup"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: config | Create restic-prune
  ansible.builtin.template:
    src: "./restic-prune.j2"
    dest: "{{ restic_bin_system_path }}/restic-prune"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0700"

- name: config | Create restic-backup cron
  ansible.builtin.cron:
    name: "restic-backup"
    minute: "{{ restic_cron_backup.minute }}"
    hour: "{{ restic_cron_backup.hour }}"
    day: "{{ restic_cron_backup.day }}"
    weekday: "{{ restic_cron_backup.weekday }}"
    month: "{{ restic_cron_backup.month }}"
    cron_file: restic
    user: root
    job: "{{ restic_bin_system_path }}/restic-backup"

- name: config | Create restic-prune cron
  ansible.builtin.cron:
    name: "restic-prune"
    minute: "{{ restic_cron_prune.minute }}"
    hour: "{{ restic_cron_prune.hour }}"
    day: "{{ restic_cron_prune.day }}"
    weekday: "{{ restic_cron_prune.weekday }}"
    month: "{{ restic_cron_prune.month }}"
    cron_file: restic
    user: root
    job: "{{ restic_bin_system_path }}/restic-prune"

- name: config | "Cleanup OLD crontab crons"
  ansible.builtin.cron:
    name: "{{ item }}"
    state: absent
  with_items:
    - "restic-backup"
    - "restic-prune"
