---
- name: Install restic from package
  ansible.builtin.package:
    name: "{{ restic_package_name }}"
    state: present

- name: Create restic directories
  ansible.builtin.file:
    state: "directory"
    path: "{{ item }}"
    mode: "0750"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
  with_items:
    - "{{ restic_config_path }}"
