---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv'
  armv6l: 'armv'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

restic_releases: "https://github.com/restic/restic/releases/download"
restic_package: "restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch }}"
restic_url: "{{ restic_releases }}/v{{ restic_version }}/{{ restic_package }}.bz2"

restic_dependencies:
  - "bzip2"

restic_package_name:
  - "restic"
