---
- name: Prepare the Molecule Test Resources
  hosts: all

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: update ca-certificates and install cron
      package:
        name:
          - "ca-certificates"
          - "cron"
        state: latest
      when: ansible_os_family == "Debian"

    - name: update ca-certificates and install cron
      package:
        name:
          - "ca-certificates"
          - "cronie"
        state: latest
      when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"
