---
- name: Prepare the Molecule Test Resources
  hosts: all

  tasks:
    - name: update ca-certificates and install cron
      package:
        name:
          - "ca-certificates"
          - "cron"
        state: latest
      when: ansible_os_family == "Debian"

    - name: update ca-certificates and install cron
      package:
        name:
          - "ca-certificates"
          - "cronie"
        state: latest
      when: ansible_os_family == "RedHat" or ansible_os_family == "Rocky"
