---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test restic binary system link
      ansible.builtin.command: '/usr/local/bin/restic version'
      register: restic_version
      changed_when: restic_version.rc != 0
      when: ansible_os_family == "Redhat"

    - name: Test restic binary system link
      ansible.builtin.command: '/usr/bin/restic version'
      register: restic_version
      changed_when: restic_version.rc != 0
      when: ansible_os_family == "Debian"

    - name: Test if restic-backup script exists
      ansible.builtin.lineinfile:
        name: '/usr/local/bin/restic-backup'
        line: '# get config through environment variables'
        state: present
      check_mode: true
      register: file_restic_backup
      failed_when: (file_restic_backup is changed) or (file_restic_backup is failed)

    - name: verify restic-backup filemode
      ansible.builtin.file:
        name: '/usr/local/bin/restic-backup'
        owner: "root"
        group: "root"
        mode: "0700"
      check_mode: true
      register: mode_restic_backup
      failed_when: (mode_restic_backup is changed) or (mode_restic_backup is failed)

    - name: Test if restic-prune script exists
      ansible.builtin.lineinfile:
        name: '/usr/local/bin/restic-prune'
        line: '# get config through environment variables'
        state: present
      check_mode: true
      register: file_restic_prune
      failed_when: (file_restic_prune is changed) or (file_restic_prune is failed)

    - name: verify restic-prune filemode
      ansible.builtin.file:
        name: '/usr/local/bin/restic-prune'
        owner: "root"
        group: "root"
        mode: "0700"
      check_mode: true
      register: mode_restic_prune
      failed_when: (mode_restic_prune is changed) or (mode_restic_prune is failed)

    - name: Test if restic-env exists
      ansible.builtin.lineinfile:
        name: '/etc/restic/restic-env'
        line: '# Environment file for restic settings'
        state: present
      check_mode: true
      register: file_restic_env
      failed_when: (file_restic_prune is changed) or (file_restic_prune is failed)

    - name: verify restic-env filemode
      ansible.builtin.file:
        name: '/etc/restic/restic-env'
        owner: "root"
        group: "root"
        mode: "0700"
      check_mode: true
      register: mode_restic_env
      failed_when: (mode_restic_env is changed) or (mode_restic_env is failed)

    - name: Test if restic-includes exists
      ansible.builtin.lineinfile:
        name: '/etc/restic/restic-includes'
        line: '# https://restic.readthedocs.io/en/latest/040_backup.html#including-files'
        state: present
      check_mode: true
      register: file_restic_includes
      failed_when: (file_restic_includes is changed) or (file_restic_includes is failed)

    - name: verify restic-includes filemode
      ansible.builtin.file:
        name: '/etc/restic/restic-includes'
        owner: "root"
        group: "root"
        mode: "0700"
      check_mode: true
      register: mode_restic_includes
      failed_when: (mode_restic_includes is changed) or (mode_restic_includes is failed)

    - name: Test if restic-excludes exists
      ansible.builtin.lineinfile:
        name: '/etc/restic/restic-excludes'
        line: '# https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files'
        state: present
      check_mode: true
      register: file_restic_excludes
      failed_when: (file_restic_excludes is changed) or (file_restic_excludes is failed)

    - name: verify restic-excludes filemode
      ansible.builtin.file:
        name: '/etc/restic/restic-excludes'
        owner: "root"
        group: "root"
        mode: "0700"
      check_mode: true
      register: mode_restic_excludes
      failed_when: (mode_restic_excludes is changed) or (mode_restic_excludes is failed)

    - name: verify restic backup cron
      ansible.builtin.cron:
        name: "restic-backup"
        minute: "5"
        hour: "*"
        day: "*"
        weekday: "*"
        month: "*"
        cron_file: "restic"
        user: root
        job: "/usr/local/bin/restic-backup"
      check_mode: true
      register: cron_restic_backup
      failed_when: (cron_restic_backup is changed) or (cron_restic_backup is failed)

    - name: verify restic prune cron
      ansible.builtin.cron:
        name: "restic-prune"
        minute: "35"
        hour: "5"
        day: "*"
        weekday: "*"
        month: "*"
        cron_file: "restic"
        user: root
        job: "/usr/local/bin/restic-prune"
      check_mode: true
      register: cron_restic_prune
      failed_when: (cron_restic_prune is changed) or (cron_restic_prune is failed)

    - name: "Verfiy OLD crons are gone"
      ansible.builtin.cron:
        name: "{{ item }}"
        state: absent
      with_items:
        - "restic-backup"
        - "restic-prune"
      check_mode: true
      register: molecule_old_cron
      failed_when: (molecule_old_cron is changed) or (molecule_old_cron is failed)

    - name: verify restic backup
      ansible.builtin.command: '/usr/local/bin/restic-backup'
      register: restic_backup
      changed_when: restic_backup.rc != 0

    - name: verify restic prune
      ansible.builtin.command: '/usr/local/bin/restic-prune'
      register: restic_prune
      changed_when: restic_prune.rc != 0
