---
# Ansible managed

name: "Ansible Molecule (2.10/package)"

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '35 18 18 * *'

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          command: lint
          scenario: "package"
          ansible: "2.10"

  "package_210":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, fedora33, fedora34, fedora35, centos7, centos8, centos8-stream, ubi8, rockylinux8, almalinux8, amazonlinux]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "package"
          ansible: "2.10"
          platform: "${{ matrix.platform }}"
